# Generated by Django 3.1.7 on 2021-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_feedbackarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackarticles',
            name='stars',
            field=models.IntegerField(default=1),
        ),
    ]
