# Generated by Django 3.1.7 on 2021-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
