# Generated by Django 3.1.7 on 2021-04-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.RenameModel(
            old_name='FeedbackArticles',
            new_name='FeedbackArticle',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
