# Generated by Django 3.1.7 on 2021-04-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(null=True, upload_to='doctor_images'),
        ),
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='service_images'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='news_article_cover'),
        ),
    ]
