# Generated by Django 3.1.7 on 2021-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210415_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUSForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('departament', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
