# Generated by Django 3.1.7 on 2021-04-15 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_writeusform'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeusform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
