# Generated by Django 3.1.7 on 2021-04-16 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_contactusform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackarticle',
            name='stars',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
