# Generated by Django 3.1.7 on 2021-04-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210416_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusform',
            old_name='message',
            new_name='messageOne',
        ),
    ]
