# Generated by Django 3.1.7 on 2021-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210416_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
